const BOOK_DATA = [
  {
    "name":"Ana",
    "author":"Maksim Gorki",
    "price":12,
    "image":"ana.png",
    "mail":"ozanakts58@gmail.com",
    "sms":"053745799629",
  },
  {
    "name":"Cimri",
    "author":"Moliere",
    "price":6,
    "image":"cimri.png",
    "mail":"ozanakts58@outlook.com",
    "sms":"0534354684",
  },
  {
    "name":"İnsancıklar",
    "author":"Fyodor Dostoyevski",
    "price":8,
    "image":"insancıklar.png",
    "mail":"ali@gmail.com",
    "sms":"05374579629",
  },
  {
    "name":"Kumarbaz",
    "author":"Dostoyevski",
    "price":5,
    "image":"kumarbaz.png",
    "mail":"asli@gmail.com",
    "sms":"05374579629",
  },
  {
    "name":"Kürk Mantolu Madonna",
    "author":"Sebahattin Ali",
    "price":10,
    "image":"madonna.png",
    "mail":"ahmet@ahmet.com",
    "sms":"05374579629",
  },
  {
    "name":"Huzursuzluk",
    "author":"Zülfü Livaneli",
    "price":9,
    "image":"huzursuzluk.png",
    "mail":"kerime@gmail.com",
    "sms":"05374579629",
  },
  {
    "name":"Binboğalar Efsanesi",
    "author":"Yaşar Kemal",
    "price":17,
    "image":"efsanesi.png",
    "mail":"ozanakts@gmail.com",
    "sms":"05374579629",
  },
  {
    "name":"İnce Memed 1",
    "author":"Yaşar Kemal",
    "price":15,
    "image":"memed.png",
    "mail":"ozan@gmail.com",
    "sms":"05374579629",
  },
  {
    "name":"Bir Ses Böler Geceyi",
    "author":"Ahmet Ümit",
    "price":13,
    "image":"geceyi.png",
    "mail":"ozana@gmail.com",
    "sms":"05374579629",
  },
  {
    "name":"Saatleri Ayarlama Enstitüsü",
    "author":"Ahmet Hamdi Tanpınar",
    "price":28,
    "image":"enstütü.png",
    "mail":"ozanakts5858@gmail.com",
    "sms":"05374579629",
  },
  {
    "name":"Yeni Dünya",
    "author":"Sebahattin Ali",
    "price":14,
    "image":"madonna.png",
    "mail":"ozanakts58@gmail.com",
    "sms":"05374579629",
  },
  {
    "name":"Kuyucaklı Yusuf",
    "author":"Sebahattin Ali",
    "price":21,
    "image":"kuyucaklı.png",
    "mail":"ozanakts58@gmail.com",
    "sms":"053749629",
  },
  {
    "name":"İçimizdeki Şeytan",
    "author":"Sebahattin Ali",
    "price":18,
    "image":"icimizdeki.png",
    "mail":"ozanakts58@gmail.com",
    "sms":"053745456629",
  },
  {
    "name":"Küçük Burjuvalar",
    "author":"Maksim Gorki",
    "price":17,
    "image":"burjuva.png",
    "mail":"ozanakts58@gmail.com",
    "sms":"0531445664",
  },
  {
    "name":"Silo",
    "author":"Hugh Howey",
    "price":12,
    "image":"silo.png",
    "mail":"ozanakts58@gmail.com",
    "sms":"05374579629",
  },

];